numpy condenses the vector operations i wrote into one liners
also in optimized C, faster, safer, vectorized, memory aware

this session is focused on numpy arrays as vectors (1D only)
and how they differ from python lists in ways ML cares about

In [1]:
import numpy as np

v_list = [1, 2, 3]
v_np = np.array([1, 2, 3])

In [2]:
type(v_list)

list

In [3]:
type(v_np)

numpy.ndarray

In [4]:
print(v_np)
print(v_np.shape)
print(v_np.dtype)

[1 2 3]
(3,)
int64


# basic numpy
shape tells us this is a 1D array with 3 elements
comma MATTERS! (3,) is a 1-tuple
    tuples: sequence type of pairs, described array's dimensions

dtype tells us every element is stored as a fixed size 64 bit integer
python lists store references to full objects

In [5]:
print(v_list * 2)
print(v_np * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
u_np = np.array([10, 20, 30])
print(v_np + u_np)

u_list = [10, 20, 30]
print(v_list + u_list)

# reminder - python lists use sequence rules and concatenate
# numpy arrays use vector math rules (elementwise)

[11 22 33]
[1, 2, 3, 10, 20, 30]


In [7]:
x = np.array([1, 2, 3])
y = x / 2
print(y)
print(y.dtype)

[0.5 1.  1.5]
float64


In [8]:
x32 = np.array([1, 2, 3], dtype=np.float32)
print(x32.dtype)
print((x32 / 2).dtype)

float32
float32


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b) # element wise - attention mechanisms
print(a @ b) # dot products
print(np.dot(a, b)) # dot products

[ 4 10 18]
32
32


In [10]:
a = np.array([1, 2, 3])
print(a.shape)

s = a @ a
print(s, type(s))

(3,)
14 <class 'numpy.int64'>


# technically, the dot product is |u||v|cos(theta)
cos(theta) indicates properties

we normalize (scale control) because otherwise, dot products
are not useful indicators of directional/angular similarity
since magnitude would dominate, not direction. training
can crank magnitudes up and explode our similarity scores

# unit vector = vector with norm 1


In [12]:
# normalizing unit vector
uv = v_np/np.linalg.norm(v_np)
print(uv)
print(np.linalg.norm(uv))

[0.26726124 0.53452248 0.80178373]
1.0
